name: My Issue
description: File a Issue.
title: "[Issue]: "
labels: 
  - bug
projects:
  - ZebNoid/template_test
assignees:
  - ZebNoid
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Issue
  - type: input
    id: version-tag
    attributes:
      label: Version?
      description: Tell us which version?
      placeholder: Version
    validations:
      required: true
  - type: dropdown
    id: react-device
    attributes:
      label: Device?
      description: On which device you running?
      multiple: true
      options:
        - Android
        - iOS
        - Neither
    validations:
      required: true
  - type: textarea
    id: react-doctor
    attributes:
      label: React Doctor?
      description: Tell us, command output `npx react-native doctor`?
      placeholder: Tell us what `npx react-native doctor` says!
    validations:
      required: true
  - type: textarea
    id: react-info
    attributes:
      label: React Info?
      description: Tell us, command output `npx react-native info`?
      placeholder: Tell us what `npx react-native info` says!
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        - What did happen?
        - What did you expect to happen?
        - Give as much detail
      placeholder: |
        - Tell us what you see!
        - What did happen?
        - What did you expect to happen?
        - Give as much detail
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Logs
      render: shell
  - type: textarea
    id: code
    attributes:
      label: Code which cause a issue
      description: Please copy and paste any relevant Code. This will be automatically formatted into TypeScript code, so no need for backticks.
      placeholder: TypeScript code
      render: typescript
  - type: checkboxes
    id: check
    attributes:
      label: Check
      options:
        - label: I have read [documentation](https://github.com/ZebNoid/template_test/README.md)
          required: true
        - label: I have tried [Troubleshoots](https://github.com/ZebNoid/template_test/README.md#Troubleshoots)
          required: true
        - label: | 
            - I have tried `reset cache`
            - `npm cache verify`
            - `npm cache clean --force`
          required: true
        - label: I have tried `completely stop application on device` and `stop React server`
          required: true
    validations:
      required: true
